// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnxdlrpwqwmksjpekyxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdueGRscnB3cXdta3NqcGVreXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMDkyNzYsImV4cCI6MjA0OTg4NTI3Nn0.dJGuoCzh55ekHEq5j9Ut9xWXXnI8265inxuS7_HePoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);